name: 'Check issues'
description: 'Check issues against repository guidelines and comment with any corrective steps.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: check-circle
  color: gray-dark
